### ISSUE TITLE
system/script/args is a block when script called from command line

### ISSUE THREAD

**Issue by Dobeash** [Oldes/Rebol3#53] opened 2022-09-22 01:36 UTC
Create a script as follows:
```
Rebol []
print type? system/script/args
```
then invoke from command line with `rebol3-base-windows-x64.exe script.r 1`.

Note that under other Redbol variants (Atronix, Red) it is a string, and is also a string if called from another script using `do/args`.

**Comment by Oldes** [comment] 2022-09-22 09:25
This issue is duplicate of your previous issue, which I transferred to the dedicated issue repository, where are also other related issues... and my answer, why it would be wrong, when it would be just a  string. And that you may pass whatever into `do/args`, not just a string.

**Comment by Oldes** [comment] 2022-09-22 09:26
The previous issue is here: https://github.com/Oldes/Rebol-issues/issues/2519

**Closed by Oldes** 2022-09-22 09:25 UTC
Labels: duplicate

**Comment by Oldes** [comment] 2022-09-22 09:27
Btw.. I don't care about Atronix version. It is a dead branch quite a long time already.

**Comment by Dobeash** [comment] 2022-09-22 12:49
> duplicate of your previous issue, which I transferred to the dedicated issue repository

Ah, that explains it ... thought I didn't submit it when I couldn't find it.
